### ISSUE TITLE
Addresses are duplicated

### ISSUE THREAD

**Issue by gordienko** [spree-contrib/spree_address_book#128]
When ordering, addresses are periodically duplicated. And always specify the already existing address. In what place is the creation of a new address? Is it possible to prevent duplicate creation there?
![default](https://user-images.githubusercontent.com/207153/45589460-76595400-b92e-11e8-9ead-0f7a3a903fc3.png)

- spree 3.6.4
- spree_address_book 3.2.0.alpha

**Comment by kaliszKrzysztof** [comment]
Also experienced such an action.

Steps to reproduce:
  1. Add address in the Account page
  2. Select previously added address in Checkout
  3. Start a new order, complete the checkout and go to the store
  4. Start a new order (just add any product to cart)
  5. The duplicated address should appear in the Account page

- spree 3.6.4

**Comment by AhmedAliIbrahim** [comment]
any updates ?
