### ISSUE TITLE
Move to spree_contrib?

### ISSUE THREAD

**Issue by wdspkr** [spree-contrib/spree_address_book#83]
We would like to see this gem actively maintained and therefore ask, if you'd be willing to move the repo to spree_contrib? That would be very much appreciated. 
What do you think @tvdeyen , wouldn't that be a good idea?

**Comment by jumph4x** [comment]
I am in close correspondence with @romul regarding this gem, as it was originally sponsored by us. 

I'm sure he won't mind. Give him some time as he is currently on a vacation. Cheers!

**Comment by romul** [comment]
Done.
